# makeCacheMatrix and cacheSolve functions will generate an inverse matrix for 
# an inputted invertible matrix and caches the results. If the matrix object is
# changed, sets the inverse matrix cache to null and recalculates the inverse
# matrix
# sample calls:
# m <- makeCacheMatrix(matrix(c(10,0,0,20), nrow=2, ncol=2))
# cacheSolve(m)
 

# CacheMatrix: Creates a matrix object and caches its inverse matrix
# inputs: must be an invertible matrix
# List of functions returned:
#  get : retrieves the matrix object 
#  set : Used to change the matrix object and resets the inverse matrix to null
#  getinverse: retrieves the inverse matrix from cache
#  setinverse: stores the inverse matrix results 

makeCacheMatrix <- function(x = matrix()) {
        s <- NULL  
        set <- function(y){
                x <<- y
                s <<- NULL
        }
        get <- function() x
        setinverse <- function(solve) s <<- solve
        getinverse <- function() s
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}        


# cacheSolve computes the inverse matrix for new matrix otherwise retrieves 
# the cache result
# input: matrix object generated by makeCacheMatrix
 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        s <- x$getinverse()  
        if(!is.null(s)) {
                message("getting cached inverse matrix")
                return(s)
        }
        data <- x$get() 
        s <- solve(data,...)   #calculates the inverse matrix
        x$setinverse(s)  # stores the inverse matrix 
        s
        
}
